### ISSUE TITLE
 ./app/libs/uuid/uuid.lua:29: libuuid.so nofind

### ISSUE THREAD

**Issue by yingnierxiao** [sumory/openresty-china#3]
C]: in function 'require'
        /home/openresty-china/./app/main.lua:8: in function </home/openresty-china/./app/main.lua:1>, client: 117.25.121.209, server: , request: "GET /index HTTP/1.1", host: "45.32.32.154"
2016/03/26 04:48:36 [error] 5030#0: *8 lua entry thread aborted: runtime error: ./app/libs/uuid/uuid.lua:29: libuuid.so: cannot open shared object file: No such file or directory
stack traceback:
coroutine 0:

**Comment by lhmwzy** [comment]
请装uuid模块
https://sourceforge.net/projects/libuuid/

**Comment by sumory** [comment]
找不到libuuid.so解决方案：

OpenResty China现在依赖libuuid来生成一些id，centos用户可尝试使用`yum install  libuuid-devel`安装，其他请自行google对应平台的安装方式。
