### ISSUE TITLE
没有一个统一的错误处理页，比如我的数据库链接帐号密码错误，应该路由到错误页。

### ISSUE THREAD

**Issue by wanderpub** [sumory/openresty-china#4]
如题

**Comment by sumory** [comment]
错误处理全在[这里](https://github.com/sumory/openresty-china/blob/master/app/main.lua#L58)，当前的实现是返回“unknown error”，然后Nginx日志记录错误。你可以自定义成你想要的样子，比如跳转到某个错误页。
